CREATE TABLE `servicerating` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`email` VARCHAR(100) NULL DEFAULT NULL,
	`fullName` VARCHAR(100) NULL DEFAULT NULL,
	`serviceRating` INT(11) NULL DEFAULT NULL,
	`foodRating` INT(11) NULL DEFAULT NULL,
	`atmosRating` INT(11) NULL DEFAULT NULL,
	`comments` VARCHAR(500) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;
