CREATE TABLE `timinglog` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`timelogged` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`user` VARCHAR(50) NULL DEFAULT NULL,
	`pageID` VARCHAR(50) NULL DEFAULT NULL,
	`att1` VARCHAR(50) NULL DEFAULT NULL,
	`timing1` VARCHAR(50) NULL DEFAULT NULL,
	`att2` VARCHAR(50) NULL DEFAULT NULL,
	`timing2` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
