CREATE TABLE `yesnolog` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`articleid` INT(11) NOT NULL DEFAULT '0',
	`result` VARCHAR(50) NOT NULL DEFAULT '0',
	`ipadd` VARCHAR(50) NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;


CREATE TABLE `whyanswerlog` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`mytime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`articleid` INT(11) NULL DEFAULT NULL,
	`result` VARCHAR(500) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;
